### 401 Unauthorised due to invalida PIN
POST http://localhost:3000/v1/api/pin/validate HTTP/1.1
content-type: application/json

{
    "pin": "eiei"
}
### 200
POST http://localhost:3000/v1/api/pin/validate HTTP/1.1
content-type: application/json

{
    "pin": "132495"
}

### http 400
POST http://localhost:3000/v1/api/pin/validate HTTP/1.1
content-type: application/json

{
    "body": "eiei"
}
### http 400
POST http://localhost:3000/v1/api/pin/validate HTTP/1.1
content-type: application/json

{
    "pin": null,
}
### http 400
POST http://localhost:3000/v1/api/pin/validate HTTP/1.1
content-type: application/json

{
    "pin": "",
}

### http 401
POST http://localhost:3000/v1/api/pin/validate HTTP/1.1
content-type: application/json

{
    "pin": "22",
}

