name: Golden Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golden_test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: 'circleci/xvfb:latest'
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install libGL (required for running tests)
        run: sudo apt-get install libgl1-mesa-glx -y

      - name: Install AVD dependencies (for emulator)
        run: sudo apt-get update -y && sudo apt-get install -y lib32stdc++6 lib32z1 android-tools-adb android-tools-fastboot

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: "-no-window"

      - name: Wait for Android Emulator to start
        run: adb wait-for-device

      - name: Run flutter doctor (check Flutter and Android setup)
        run: flutter doctor

      - name: Run Flutter Golden Tests
        run: flutter test --update-goldens

      - name: Store Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test/
