name: Flutter Golden Tests for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golden_test_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install additional macOS dependencies
        run: brew install imagemagick  # ImageMagick is used for image processing

      - name: Run Flutter Golden Tests with Custom Comparator
        run: flutter test --update-goldens

      - name: Store Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: golden-test-results
          path: test/
