name: Flutter Golden Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golden_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install libGL (required for running tests)
        run: sudo apt-get install libgl1-mesa-glx -y

      - name: Run Flutter Golden Tests with Custom Comparator
        run: flutter test
