---
name: Golden Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3
      - run: flutter --version | flutter devices
      - name: Install dependencies
        run: flutter pub get
      - name: Install dependencies for consistent rendering
        run: >
          sudo apt-get update

          sudo apt-get install -y libgtk-3-dev libglib2.0-dev libpango1.0-dev libatk1.0-dev libcairo2-dev fonts-droid-fallback
      - name: Run golden tests
        run: flutter test --tags=golden
        env:
          FONTCONFIG_FILE: /etc/fonts/fonts.conf
          HOME: /github/home
          CI: true
      - name: Compare Golden Files
        run: >
          git diff --exit-code golden/ || (echo "Golden files do not match!" && exit
          1)
      - name: Upload Golden File Differences
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: golden-diff
          path: golden/
      - name: Upload test failures
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-failures
          path: /home/runner/work/mobiletesting/mobiletesting/test/ui_test/failures
