name: Golden Test iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.24.3
        
    - run: flutter --version | flutter devices

    - name: Install dependencies
      run: flutter pub get

    - name: Run golden tests
      run: flutter test --tags=golden
      
    - name: Upload test failures
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-failures
        path: /home/runner/work/mobiletesting/mobiletesting/test/ui_test/failures
