name: Maestro iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install --project-directory=ios

      - name: Build iOS app
        run: flutter build ios --simulator --no-codesign

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 14 Pro"
          flutter emulators --launch apple_ios_simulator

      - name: Run Maestro Test Action
        run: maestro test
