name: Run Api Jest Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  node_api_jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      
      - name: Into api folder
        run: cd api

      - name: Install dependencies
        run: npm install

      - name: Run jest tests
        run: npm test